### PR TITLE
Socket IO using boost udp sockets

### PR DESCRIPTION
**Pull request by HaMster21**
Connected to #13 

It seems like the `noexcept`keyword is not supported, even in VisualStudio 2013 Update 4 VC++ compiler. So we'll either have to wait for VisualStudio 2015 or build with gcc/clang on Windows.

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/elmo-net/overlay-routing/pull/16%23issuecomment-84142754%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/elmo-net/overlay-routing/pull/16%23issuecomment-84142754%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ca%20href%3D%5C%22http%3A//app.review.ninja/elmo-net/overlay-routing/pull/16%5C%22%20target%3D%5C%22_blank%5C%22%3E%3Cimg%20src%3D%5C%22http%3A//app.review.ninja/32309933/pull/16/badge%5C%22%20alt%3D%5C%22ReviewNinja%5C%22/%3E%22%2C%20%22created_at%22%3A%20%222015-03-20T20%3A54%3A58Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8714728%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/review-ninja%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/elmo-net/overlay-routing/pull/16#issuecomment-84142754'>General Comment</a></b>
- <a href='https://github.com/review-ninja'></a> <a href="http://app.review.ninja/elmo-net/overlay-routing/pull/16" target="_blank">ReviewNinja

<a href='https://www.codereviewhub.com/elmo-net/overlay-routing/pull/16?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/elmo-net/overlay-routing/pull/16?approve=1'></a>&nbsp;<a href='https://github.com/elmo-net/overlay-routing/pull/16'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/elmo-net/overlay-routing/pull/16" target="_blank">ReviewNinja

**Comment by HaMster21** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/elmo-net/overlay-routing/pull/16'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by HaMster21** [comment]
There seems to be an include problem with fakeit. Extending the test with fakeit and catch used, gives compiler error for fakeit, assumingly because the configuration in the fakeit.cmake module doesn't include files correctly.

**Comment by HaMster21** [comment]
The CI still fails to include fakeit correctly :frowning:

**Comment by HaMster21** [comment]
Since this is working so far and I plan to create a specification document next, I'll merge this and get on the work later again

**Pull request merged**
